# Generated by Django 4.1 on 2022-09-20 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ropa',
            old_name='descripción',
            new_name='descripcion',
        ),
    ]
